export interface DemandeStage {
    _id: String,
    title: String,
    studentName: String,
    studentPresentation: String,
    school: String,
    startDate: String,
    endDate: String,
    program: String,
    stageType: String,
    hoursPerWeek: Number,
    additionalInfo: String,
    published: Boolean,
    paid: String,
    active: Boolean,
    skills: String,
    region: String,
    activitySector: String,
    city: String,
    linkToResume: String,
    __v: Number
}