import { DemandeStage } from "./demande-stages";

export const DEMANDESTAGES:DemandeStage[] = [
    {
    __id: '1',
    title: 'Intégrateur Web',
    description: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    enterprise: 'Desjardins',
    startDate: '21/3/2022',
    endDate: '21/06/2022',
    program: 'Intégration Web',
    requirements: 'les requis',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    paid: "À la discrétion de l'entreprise",
    skills: 'HTML, CSS',
    published: true,
    region: 'Mauricie',
    activitySector: "Technologie de l'information",
    city: 'Trois-Rivières',
    studentName: 'Steve Rogers',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'Cegep de Trois-Rivières',
    linkToResume: 'link.pdf'
    },
    {
    __id: '2',
    title: 'Designer Web',
    description: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    enterprise: 'Rum&Code',
    startDate: '21/3/2022',
    endDate: '21/06/2022',
    program: 'Design',
    requirements: 'les requis',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    paid: "À la discrétion de l'entreprise",
    skills: 'Adobe Illustrator, Photoshop, Adobe After Effect ',
    published: true,
    region: 'Mauricie',
    activitySector: "Technologie de l'information",
    city: 'Shawinigan',
    studentName: 'Tony Stark',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'Cegep de Trois-Rivières',
    linkToResume: 'link.pdf'
    },
    {
    __id: '3',
    title: 'Stagiaire en Marketing',
    description: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    enterprise: 'Balou Interactive',
    startDate: '21/3/2022',
    endDate: '21/06/2022',
    program: 'BAC en Marketing',
    requirements: 'les requis',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    paid: "À la discrétion de l'entreprise",
    skills: 'HTML, CSS',
    published: true,
    region: 'Montérégie',
    activitySector: "Administration",
    city: 'Sainte-Martine',
    studentName: 'Peter Parker',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'UQAM',
    linkToResume: 'link.pdf'
    },
    {
    __id: '4',
    title: 'Stagiaire en Ressource Humaine',
    description: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    enterprise: 'Design Chez Paul',
    startDate: '21/03/2022',
    endDate: '21/06/2022',
    program: 'BAC en Ressource Humaine',
    requirements: 'les requis',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    paid: "À la discrétion de l'entreprise",
    skills: 'HTML, CSS',
    published: false,
    region: 'Grand Montreal',
    activitySector: "Technologie de l'information",
    city: 'Montreal',
    studentName: 'Bruce Banner',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'UDEM',
    linkToResume: 'link.pdf'
    }
]