/* import { DemandeStage } from "./demande-stages";

export const DEMANDESTAGES:DemandeStage[] = [
    {
    _id: '1',
    title: 'Intégrateur Web',
    studentName: 'Steve Rogers',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'Cegep de Trois-Rivières',
    startDate: 2022-3-21,
    endDate: '21/06/2022',
    program: 'Intégration Web',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    published: true,
    paid: ["À la discrétion de l'entreprise"],
    active: true,
    skills: ['HTML, CSS'],
    region: 'Mauricie',
    activitySector: "Technologie de l'information",
    city: 'Trois-Rivières',
    linkToResume: 'link.pdf'
    },
    {
    _id: '2',
    title: 'Intégrateur Web',
    studentName: 'Steve Rogers',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'Cegep de Trois-Rivières',
    startDate: '21/3/2022',
    endDate: '21/06/2022',
    program: 'Intégration Web',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    published: true,
    paid: ["À la discrétion de l'entreprise"],
    active: true,
    skills: ['HTML, CSS'],
    region: 'Mauricie',
    activitySector: "Technologie de l'information",
    city: 'Trois-Rivières',
    linkToResume: 'link.pdf'
    },
    {
    _id: '3',
    title: 'Intégrateur Web',
    studentName: 'Steve Rogers',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'Cegep de Trois-Rivières',
    startDate: '21/3/2022',
    endDate: '21/06/2022',
    program: 'Intégration Web',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    published: true,
    paid: ["À la discrétion de l'entreprise"],
    active: true,
    skills: ['HTML, CSS'],
    region: 'Mauricie',
    activitySector: "Technologie de l'information",
    city: 'Trois-Rivières',
    linkToResume: 'link.pdf'
    },
    {
    _id: '4',
    title: 'Intégrateur Web',
    studentName: 'Steve Rogers',
    studentPresentation: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    school: 'Cegep de Trois-Rivières',
    startDate: '21/3/2022',
    endDate: '21/06/2022',
    program: 'Intégration Web',
    stageType: 'Temps plein',
    hoursPerWeek: 35,
    additionalInfo: 'Spicy jalapeno bacon ipsum dolor amet cow meatloaf jowl leberkas turkey boudin buffalo shank landjaeger. Sirloin pancetta burgdoggen, brisket meatloaf ball tip venison beef ribs chuck rump frankfurter bacon. Tenderloin rump swine meatball. Boudin pork chop sirloin beef doner.',
    published: true,
    paid: ["À la discrétion de l'entreprise"],
    active: true,
    skills: ['HTML, CSS'],
    region: 'Mauricie',
    activitySector: "Technologie de l'information",
    city: 'Trois-Rivières',
    linkToResume: 'link.pdf'
    }
] */